### ISSUE TITLE
getting error running 'make watch'

### ISSUE THREAD

**Issue by eddyystop** [acdlite/flummox-isomorphic-demo#12]
I get the following running 'make watch' on a Ubuntu VirtualBox VM with io.js v1.6.1

...
webpack: bundle is now VALID.
Hash: 7a439141e7093b062723
Version: webpack 1.5.3
Time: 7111ms
     Asset    Size  Chunks             Chunk Names
app.min.js  316521       0  [emitted]  main
    + 224 hidden modules
nodemon lib/server/app.js
26 Mar 15:28:22 - [nodemon] v1.3.7
26 Mar 15:28:22 - [nodemon] to restart at any time, enter `rs`
26 Mar 15:28:22 - [nodemon] watching: _._
26 Mar 15:28:22 - [nodemon] starting `node --harmony lib/server/app.js`

/home/johnsz/shared/code/react/flummox-isomorphic-demo/node_modules/koa/lib/application.js:174
function *respond(next) {
         ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (../../src/server/app.js:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
26 Mar 15:28:22 - [nodemon] app crashed - waiting for file changes before starting...

**Comment by acdlite** [comment]
Hmm, are you sure you're running iojs? Looks like a generator error.

I'm _very_ close to releasing a new example project to replace this one. (Spoiler alert: it's also the documentation site.) Thank you for your patience.

**Comment by eddyystop** [comment]
'node -v' gives v1.6.1 which is a io.js semver not a node.js one.

I've evaluated several flux repos and I like the balanced abstration I see in flummox. A reflux 0.13 example would be welcome.

**Comment by acdlite** [comment]
Yep, the docs site will be a Flummox 3.x & React 0.13 pre-rendered isomorphic site. Coming very soon :)

**Comment by eddyystop** [comment]
Thanks.

FWIW, I haven't seen a makefile since I started with Node and frontend. You may lose Windows devs (and there are many enterprise ones) with make.

**Comment by acdlite** [comment]
You're right, make is not not terribly common in the Node community. Off the top of my head, I know Babel uses it: https://github.com/babel/babel

However, make is not required to use the library :) I prefer it to gulp, Grunt, etc. because it's Unix-y, it does incremental builds, and I don't have to learn a new build system for every platform. But there are plenty of gulp tutorials out there if you would prefer to use that.

**Comment by eddyystop** [comment]
I wasn't clear enough, sorry. My intent was only to point out you might lose some audience if the coming example requires a preliminary build step, before running, which uses make.

**Comment by acdlite** [comment]
Yeah, I feel ya. Maybe in the future I'll move to just using npm scripts. For now, though, there are other demos you can reference that use gulp, such as https://github.com/olegsmetanin/react_react-router_flummox_example. (I should probably collect these and put them in the docs somewhere.)
